// This file is auto-generated by @hey-api/openapi-ts


export enum EventMessageTypeModelEnum {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export enum ImpersonationResultEnum {
    NOT_SIGNED_IN = 'NotSignedIn',
    SUCCESS = 'Success',
    USER_NOT_FOUND = 'UserNotFound',
    INVALID_USER_ID = 'InvalidUserId',
    ACCESS_DENIED = 'AccessDenied'
}