// This file is auto-generated by @hey-api/openapi-ts


import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './types.gen';

export class ImpersonatorApiService {
    /**
 * @returns ImpersonationResult OK
 * @throws ApiError
 */
    public static deleteUmbracoManagementApiV1ImpersonatorApiUser(): CancelablePromise<$OpenApiTs['/umbraco/management/api/v1/impersonator-api/user']['delete']['res'][200]> {
        return __request(OpenAPI, {
    method: 'DELETE',
    url: '/umbraco/management/api/v1/impersonator-api/user',
    errors: {
        401: 'The resource is protected and requires an authentication token'
    }
});
    }
    
    /**
 * @returns string OK
 * @throws ApiError
 */
    public static getUmbracoManagementApiV1ImpersonatorApiUser(): CancelablePromise<$OpenApiTs['/umbraco/management/api/v1/impersonator-api/user']['get']['res'][200]> {
        return __request(OpenAPI, {
    method: 'GET',
    url: '/umbraco/management/api/v1/impersonator-api/user',
    errors: {
        401: 'The resource is protected and requires an authentication token'
    }
});
    }
    
    /**
 * @returns ImpersonationResult OK
 * @throws ApiError
 */
    public static putUmbracoManagementApiV1ImpersonatorApiUser(data: $OpenApiTs['/umbraco/management/api/v1/impersonator-api/user']['put']['req'] = {}): CancelablePromise<$OpenApiTs['/umbraco/management/api/v1/impersonator-api/user']['put']['res'][200]> {
        const { id } = data;
        return __request(OpenAPI, {
    method: 'PUT',
    url: '/umbraco/management/api/v1/impersonator-api/user',
    query: {
        id
    },
    errors: {
        401: 'The resource is protected and requires an authentication token'
    }
});
    }
    
}