// This file is auto-generated by @hey-api/openapi-ts


export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type ImpersonationResult = 'NotSignedIn' | 'Success' | 'UserNotFound' | 'InvalidUserId' | 'AccessDenied';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type $OpenApiTs = {
    '/umbraco/management/api/v1/impersonator-api/user': {
        delete: {
            res: {
                /**
 * OK
 */
                200: ImpersonationResult;
            };
        };
        get: {
            res: {
                /**
 * OK
 */
                200: string;
            };
        };
        put: {
            req: {
                id?: string;
            };
            res: {
                /**
 * OK
 */
                200: ImpersonationResult;
            };
        };
    };
};