// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { EndImpersonationData, EndImpersonationErrors, EndImpersonationResponses, GetImpersonatingUserNameData, GetImpersonatingUserNameErrors, GetImpersonatingUserNameResponses, GetUsersData, GetUsersErrors, GetUsersResponses, ImpersonateData, ImpersonateErrors, ImpersonateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const endImpersonation = <ThrowOnError extends boolean = false>(options?: Options<EndImpersonationData, ThrowOnError>) => {
    return (options?.client ?? client).post<EndImpersonationResponses, EndImpersonationErrors, ThrowOnError>({
        url: '/umbraco/impersonator/api/v1/EndImpersonation',
        ...options
    });
};

export const getImpersonatingUserName = <ThrowOnError extends boolean = false>(options?: Options<GetImpersonatingUserNameData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetImpersonatingUserNameResponses, GetImpersonatingUserNameErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/umbraco/impersonator/api/v1/GetImpersonatingUserName',
        ...options
    });
};

export const getUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUsersData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUsersResponses, GetUsersErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/umbraco/impersonator/api/v1/GetUsers',
        ...options
    });
};

export const impersonate = <ThrowOnError extends boolean = false>(options?: Options<ImpersonateData, ThrowOnError>) => {
    return (options?.client ?? client).post<ImpersonateResponses, ImpersonateErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/umbraco/impersonator/api/v1/Impersonate',
        ...options
    });
};
