// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44320' | (string & {});
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type SimpleUserModel = {
    key: string;
    name?: string | null;
};

export type EndImpersonationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/impersonator/api/v1/EndImpersonation';
};

export type EndImpersonationErrors = {
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type EndImpersonationResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetImpersonatingUserNameData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/impersonator/api/v1/GetImpersonatingUserName';
};

export type GetImpersonatingUserNameErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetImpersonatingUserNameResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetImpersonatingUserNameResponse = GetImpersonatingUserNameResponses[keyof GetImpersonatingUserNameResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/impersonator/api/v1/GetUsers';
};

export type GetUsersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetUsersResponses = {
    /**
     * OK
     */
    200: Array<SimpleUserModel>;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type ImpersonateData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/impersonator/api/v1/Impersonate';
};

export type ImpersonateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type ImpersonateResponses = {
    /**
     * OK
     */
    200: unknown;
};
