// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44320' | (string & {});
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type EndImpersonationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/impersonator/api/v1/EndImpersonation';
};

export type EndImpersonationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type EndImpersonationResponses = {
    /**
     * OK
     */
    200: string;
};

export type EndImpersonationResponse = EndImpersonationResponses[keyof EndImpersonationResponses];

export type GetImpersonatingUserHashData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/impersonator/api/v1/GetImpersonatingUserHash';
};

export type GetImpersonatingUserHashErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetImpersonatingUserHashResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetImpersonatingUserHashResponse = GetImpersonatingUserHashResponses[keyof GetImpersonatingUserHashResponses];

export type ImpersonateData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/impersonator/api/v1/Impersonate';
};

export type ImpersonateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type ImpersonateResponses = {
    /**
     * OK
     */
    200: string;
};

export type ImpersonateResponse = ImpersonateResponses[keyof ImpersonateResponses];
